### PR TITLE
docs: update readme

### PR DESCRIPTION
**Pull request by delta1**
Description
---

Motivation and Context
---

How Has This Been Tested?
---

### CODE REVIEW

**Review by stringhandler — APPROVED** [review]

**Review by stringhandler — APPROVED** [review]

**Comment by delta1** [comment]
bors ping

**Comment by delta1** [comment]
bors merge

**Comment by stringhandler** [comment]
now bors!

**Comment by delta1** [comment]
will have to look into timeout settings for our tests

**Comment by delta1** [comment]
bors merge

**Comment by delta1** [comment]
bors cancel

**Comment by delta1** [comment]
bors merge

**Pull request closed without merging**
